sudo: required
services:
   - docker

before_install:
  - docker build -t ganeshvemireddi/docker-react -f Dockerfile.dev .

script:
  - docker run ganeshvemireddi/docker-react npm run test -- --coverage